<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagedPlugin>true</ManagedPlugin>
    <ManagedPluginId>myavalonia.plugin.novel.generate</ManagedPluginId>
    <ManagedPluginDirectoryName>NovelGeneratePlugin</ManagedPluginDirectoryName>
    <PluginVersion>1.0.0</PluginVersion>
    <ManagedPluginRuntimeIdentifier>win-x64</ManagedPluginRuntimeIdentifier>
    <ManagedPluginEntryType>NovelGeneratePlugin.Plugin.NovelGeneratePluginModule</ManagedPluginEntryType>
    <ManagedPluginSdkMinInclusive>3.4.0</ManagedPluginSdkMinInclusive>
    <ManagedPluginSdkMaxExclusive>4.0.0</ManagedPluginSdkMaxExclusive>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <ManagedPluginPrivatePackage Include="System.Security.Cryptography.ProtectedData" />
    <ManagedPluginPrivatePackage Include="Microsoft.Data.Sqlite.Core" />
    <ManagedPluginPrivatePackage Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <ManagedPluginPrivatePackage Include="SQLitePCLRaw.core" />
    <ManagedPluginPrivatePackage Include="SQLitePCLRaw.provider.e_sqlite3" />
    <ManagedPluginPrivatePackage Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="MyAvaloniaManagement.Plugin.Build" PrivateAssets="all" />
    <PackageReference Include="MyAvaloniaManagement.PluginSdk" />
    <PackageReference Include="MyAvaloniaManagement.Icons" />
    <ManagedPluginPrivatePackage Include="MyAvaloniaManagement.Icons" />
    <PackageReference Include="MyAvaloniaManagement.PluginSdk.UI" />
  </ItemGroup>

</Project>
